version: "3"

tasks:
  dev:
    cmds:
      - PORT=${PORT:-4173} npm run dev -- --host --port ${PORT:-4173}
  lint:
    cmds:
      - npm run lint
      - uv run ruff check scripts
  build:
    cmds:
      - npm run build
  update:
    cmds:
      - uv run scripts/update_leverage.py
      - uv run scripts/update_valuation.py
      - uv run scripts/update_eps.py
  clean:
    cmds:
      - rm -rf dist dist-ssr .vite .turbo .cache
