version: "3"

tasks:
  install:
    desc: Install all dependencies
    cmds:
      - uv sync
      - npm install

  dev:
    desc: Run backend and frontend concurrently
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Run FastAPI backend
    cmds:
      - uv run uvicorn backend.main:app --reload --port 8000

  dev:frontend:
    desc: Run Vite frontend
    cmds:
      - npm run dev

  check:
    desc: Run all quality checks (lint + typecheck + build)
    cmds:
      - task: lint
      - task: typecheck
      - task: build

  lint:
    desc: Lint Python and TypeScript
    cmds:
      - uv run ruff check .
      - npm run lint

  format:
    desc: Format all code
    cmds:
      - uv run ruff format .

  typecheck:
    desc: TypeScript type check
    cmds:
      - npm run typecheck

  build:
    desc: Build production frontend
    cmds:
      - npm run build

  update:leverage:
    desc: Update QQQ leverage metrics
    cmds:
      - PYTHONPATH=. uv run python scripts/update_leverage.py

  update:valuation:
    desc: Update NDX valuation data
    cmds:
      - PYTHONPATH=. uv run python scripts/fetch_valuation_pdr.py

  update:all:
    desc: Update all market data
    deps: [update:leverage, update:valuation]

  clean:
    desc: Remove all caches and build artifacts
    cmds:
      - rm -rf dist dist-ssr .vite .turbo .cache .ruff_cache .pytest_cache
      - find . -type d -name '__pycache__' -exec rm -rf {} +
