version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv sync
      - npm install

  dev:
    desc: Run development servers
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Run backend server
    cmds:
      - uv run uvicorn backend.main:app --reload --port 8000

  dev:frontend:
    desc: Run frontend server
    cmds:
      - npm run dev

  update:leverage:
    desc: Update leverage metrics (QQQ)
    cmds:
      - PYTHONPATH=. uv run python scripts/update_leverage.py

  update:valuation:
    desc: Update valuation (NDX price + EPS model)
    cmds:
      - PYTHONPATH=. uv run python scripts/fetch_valuation_pdr.py

  update:all:
    desc: Update leverage and valuation data
    deps: [update:leverage, update:valuation]

  build:
    desc: Build frontend
    cmds:
      - npm run build

  lint:
    desc: Lint code
    cmds:
      - uv run ruff check .
      - npm run lint

  typecheck:
    desc: Type-check frontend (no emit)
    cmds:
      - npm run typecheck

  check:
    desc: Run all quality gates (lint + typecheck)
    deps: [lint, typecheck]

  format:
    desc: Format code
    cmds:
      - uv run ruff format .

  del:cache:
    desc: Delete build/test caches (keeps node_modules and data)
    cmds:
      - rm -rf .ruff_cache .pytest_cache .mypy_cache .ipynb_checkpoints .parcel-cache .cache .turbo .vite coverage dist-ssr dist
      - find . -name '__pycache__' -type d -prune -exec rm -rf {} +
